# Site
name: "BoostKPI"
title: "BoostKPI Blog"
description: "Boost KPI articles and blog"
logo: 'assets/images/boostkpi-logo-1.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-xxxxxxxx-1'
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: contact@boostkpi.com

# Authors
authors:
  sal:
    name: Amit
    display_name: Amit
    avatar: 'assets/images/avatar-sal.png'
    email: amit@boostkpi.com
    web: https://www.boostkpi.com
    twitter:
    description: ""
  john:
    name: Kishore
    display_name: Kishore
    avatar: 'assets/images/avatar.png'
    email: kishore@boostkpi.com
    web: https://www.boostkpi.com
    twitter:
    description: ""

url: "https://blog.boostkpi.com"
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
