# Site
name: "BoostKPI"
title: "BoostKPI Blog"
description: "Explore BoostKPI Blog for cutting-edge insights on leveraging AI and data analytics to drive business growth, performance, and innovation."
logo: 'assets/images/boostkpi-logo-1.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-xxxxxxxx-1'
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: contact@boostkpi.com
default_url: https://boostkpi.com

# Exclude pages from sitemap
defaults:
  - scope:
      path: '_pages/about.md'
    values:
      sitemap: false
  - scope:
      path: '_pages/contact.md'
    values:
      sitemap: false
  - scope:
      path: '_pages/categories.md'
    values:
      sitemap: false
  - scope:
      path: '_pages/authors.html'
    values:
      sitemap: false
  - scope:
      path: '_pages/tags.md'
    values:
      sitemap: false
# Authors
authors:
  sal:
    name: Amit Manjhi
    display_name: Amit
    avatar: 'assets/images/avatar-sal.png'
    email: amit@boostkpi.com
    web: https://boostkpi.com
    twitter: https://twitter.com/boostkpi
    description: ""

url: "https://blog.boostkpi.com"
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
